name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: ['**']

jobs:
  # Build and test Go backend on all PRs and pushes to main/master
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Go backend
        run: |
          go build -v ./...
      - name: Run Go backend tests (if present)
        run: |
          if ls *.go 1> /dev/null 2>&1; then go test -v ./...; fi
      - name: Run Go backend hello world
        run: |
          timeout 5s go run main.go || true

  # Build frontend on all PRs and pushes to main/master
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm ci; fi
      - name: Run frontend hello world (placeholder)
        run: |
          echo "Hello from frontend!"

  # Format and validate Terraform on all PRs and pushes to main/master
  terraform-fmt:
    name: "Terraform Format & Validate"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        run: |
          terraform init -backend=false || true
          terraform validate || true

  # Deploy infrastructure on push to main/master only
  terraform-apply-prod:
    name: "Terraform Apply (Prod)"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: terraform-fmt
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: cd infrastructure/environments/prod && terraform init -backend-config=prod.tfbackend
      - name: Terraform Apply
        run: cd infrastructure/environments/prod && terraform apply -auto-approve
